spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      #      ddl-auto: create? ?? ???? ?? ???. update? ?? ??? ??.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
        # lazy???? ???? ? ? ?? 100?? Item? DB?? ??? ???? ????.
        # ????? 100?? ????? ? ??? ??? ??? ?? ? ? ??
        # ?? ?? ?? ??? ?? Out of Memory ??? ??? ???? ??.
        # Entity? @BatchSize?? ?? ??
        default_batch_fetch_size: 100
    jackson:
      serialization:
        fail-on-empty-beans: false
  logging:
    level:
      org.hibernate.SQL: debug
      ort.hibernate.type: trace